import typescript from "@rollup/plugin-typescript";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "src/plugin/main.ts",
  output: {
    dir: "./",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  onwarn(warning, warn) {
    // Suppress noisy third-party warning from react-icons ESM build
    if (
      warning.code === "THIS_IS_UNDEFINED" &&
      /react-icons/.test(String(warning.message) + String(warning.id ?? ""))
    ) {
      return;
    }
    warn(warning);
  },
  plugins: [
    typescript(),
    resolve({
      browser: true,
    }),
    commonjs({ include: "node_modules/**" }),
  ],
};
